version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - app-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    networks:
      - app-network

  deepseek_r1:
    image: deepseek_r1:latest
    container_name: deepseek_r1
    ports:
      - "8000:8000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge